name: Discussion Notification

on:
  workflow_dispatch:
  discussion:
    types: [created]

jobs:
  notify_associates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install apyb-bot package
      run: pip install git+https://github.com/apyb/apyb-bot.git

    - name: Notify associates
      env:
        APYB_BOT_GITHUB_TOKEN: ${{ secrets.APYB_BOT_GITHUB_TOKEN }}
        APYB_BOT_NO_REPLY_PASSWORD: ${{ secrets.APYB_BOT_NO_REPLY_PASSWORD }}
        APYB_BOT_SEND_TO: ${{ secrets.APYB_BOT_SEND_TO }}
      run: apyb-bot github:new-discussion-notification --id ${{ github.event.discussion.id }}
